#!/bin/python

name = raw_input("What is your name? ")
birthdate = raw_input("What is your birthdate? ")

age = input("What is your age? ")

print("%s your brithdate is %s" % (name, birthdate))
print("Half your age is %s" % (age / 2))
